### ISSUE TITLE
Make External IP configurable

### ISSUE THREAD

**Issue by michaeldtz** [terraform-google-modules/terraform-google-sap#14]
For security reasons many customers only want to deploy VMs without external IP addresses. Currently this is not configurable in the scripts for HANA / HANA_HA. The NetWeaver scripts already have this config option named "external_ip". 

Is there a chance to add this to the HANA / HANA_HA setups? 
I'm happy to contribute if that makes sense for this little change.

**Comment by morgante** [comment]
I'd be happy to review this addition.
