### ISSUE TITLE
Startup-script handling in examples.

### ISSUE THREAD

**Issue by michaeldtz** [terraform-google-modules/terraform-google-sap#17]
This is a minor proposal for an improvement that increases the consistency between the NW example and the HANA examples. The HANA examples use (in main.tf) for the startup-script the approach to load it from a file. This is missing in the netweaver example. 

The effect is: The HANA examples expect to get a filename to the script, while the netweaver example expects to get the scripts content. If would streamline this to the approach in the HANA example

In HANA Example:
https://github.com/terraform-google-modules/terraform-google-sap/blob/2370905a0bfa8e9e3f5a86bc13e150bcf69a771d/examples/sap_hana_simple_example/main.tf#L41

In NW Example:
https://github.com/terraform-google-modules/terraform-google-sap/blob/2370905a0bfa8e9e3f5a86bc13e150bcf69a771d/examples/netweaver_simple_example/main.tf#L43

If that makes sense i would move forward and create the changes and make the pull request.

**Comment by morgante** [comment]
Sounds good to me.
