### ISSUE TITLE
Wrong disk sizes for HANA VMs 

### ISSUE THREAD

**Issue by emmanuelsomeox** [terraform-google-modules/terraform-google-sap#18]
When creating a HANA instance the SSD and the standard disks are created with the same size.
As the Terraform is using the sap_hana.py script for HANA disk size calculation, it is be possible to retreive both values in the python script output.
Can the HANA and HANA_HA modules be updated to set the correct disk sizes ?

I would be happy to contribute and propose a change.

**Comment by morgante** [comment]
I'd be happy to review a PR.

**Comment by emmanuelsomeox** [comment]
solved by #23
